server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5434/ewm
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver